# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: Auto Assign issue to project

on:
  issues:
    types:
      - reopened
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issues to project
      uses: Senzing/github-action-add-issue-to-project@main
      with:
        project: 'https://github.com/orgs/Senzing/projects/2'
        column_name: 'Backlog'
