# Based on
# - https://docs.github.com/en/actions/guides/adding-labels-to-issues
# - https://github.com/andymckay/labeler

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Simple Issue Labeler
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: "triage"
