name: add to project community dependabot

on:
  pull_request:
    branches: [main]

permissions:
  repository-projects: write

jobs:
  add-to-project-dependabot:
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project-dependabot.yaml@v2
    with:
      project: ${{ vars.SENZING_PROJECT_COMMUNITY }}
